(() => {
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const loader=$('#loader'); window.addEventListener('load',()=>setTimeout(()=>{loader.style.opacity='0';loader.style.visibility='hidden'},1150));
const drawer=$('.drawer'), menu=$('.menu'); menu?.addEventListener('click',()=>drawer.classList.add('open')); $('.drawer-close')?.addEventListener('click',()=>drawer.classList.remove('open')); $$('.drawer a').forEach(a=>a.addEventListener('click',()=>drawer.classList.remove('open'))); window.addEventListener('keydown',e=>{if(e.key==='Escape'){drawer.classList.remove('open');closeModal()}});
const modal=$('#authModal'); const closeModal=()=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}; const openModal=()=>{modal.classList.add('open');modal.setAttribute('aria-hidden','false')}; $$('[data-open-auth]').forEach(b=>b.addEventListener('click',openModal)); $('.modal-close')?.addEventListener('click',closeModal); modal?.addEventListener('click',e=>{if(e.target===modal)closeModal()});
$('#authForm')?.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const user={name:fd.get('name').trim(),email:fd.get('email').trim().toLowerCase(),phone:fd.get('phone').trim(),createdAt:new Date().toISOString()};localStorage.setItem('btya_demo_account',JSON.stringify(user));$('#authStatus').textContent='Account created locally. Membership still requires a separate application and approval.';e.currentTarget.reset()});
// --- Three.js: a quiet, responsive particle planet + luminous contour field ---
const mount=$('#webgl'); if(!mount||!window.THREE)return;
const scene=new THREE.Scene(); scene.fog=new THREE.FogExp2(0x08100c,.045); const camera=new THREE.PerspectiveCamera(38,innerWidth/innerHeight,.1,100);camera.position.set(0,0,12);
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;mount.appendChild(renderer.domElement);
const group=new THREE.Group();scene.add(group);
const count=innerWidth<700?1500:3000;const pos=new Float32Array(count*3),sizes=new Float32Array(count),phase=new Float32Array(count);
for(let i=0;i<count;i++){const r=4.3*Math.pow(Math.random(),.42), a=Math.random()*Math.PI*2, z=Math.random()*2-1, q=Math.sqrt(1-z*z);pos[i*3]=r*q*Math.cos(a);pos[i*3+1]=r*z;pos[i*3+2]=r*q*Math.sin(a);sizes[i]=.7+Math.random()*1.8;phase[i]=Math.random()*6.28}
const pg=new THREE.BufferGeometry();pg.setAttribute('position',new THREE.BufferAttribute(pos,3));pg.setAttribute('aSize',new THREE.BufferAttribute(sizes,1));pg.setAttribute('aPhase',new THREE.BufferAttribute(phase,1));
const pm=new THREE.ShaderMaterial({transparent:true,depthWrite:false,blending:THREE.AdditiveBlending,uniforms:{uTime:{value:0},uPointer:{value:new THREE.Vector2()}},vertexShader:`attribute float aSize;attribute float aPhase;uniform float uTime;uniform vec2 uPointer;varying float vA;void main(){vec3 p=position;float d=length(p.xz);p.y+=sin(d*1.8+uTime*.35+aPhase)*.055;float push=max(0.,1.-distance(p.xy,vec2(uPointer.x*3.,uPointer.y*2.))*0.45);p.z+=push*.35;vec4 mv=modelViewMatrix*vec4(p,1.);gl_PointSize=aSize*(110./-mv.z);gl_Position=projectionMatrix*mv;vA=.35+.65*sin(aPhase+uTime*.8);}`,fragmentShader:`varying float vA;void main(){float d=distance(gl_PointCoord,vec2(.5));float a=smoothstep(.5,.05,d);gl_FragColor=vec4(.55,1.,.32,a*vA*.55);}`});
const particles=new THREE.Points(pg,pm);group.add(particles);
const ring=new THREE.Mesh(new THREE.TorusGeometry(3.55,.006,8,220),new THREE.MeshBasicMaterial({color:0xc9ff53,transparent:true,opacity:.22}));ring.rotation.x=Math.PI*.38;group.add(ring);
const coreGeo=new THREE.IcosahedronGeometry(2.15,2);const coreMat=new THREE.ShaderMaterial({wireframe:true,transparent:true,opacity:.18,uniforms:{uTime:{value:0}},vertexShader:`uniform float uTime;varying float v;void main(){vec3 p=position;float n=sin(position.x*3.+uTime*.3)*sin(position.y*2.+uTime*.2);p+=normal*n*.025;v=n;gl_Position=projectionMatrix*modelViewMatrix*vec4(p,1.);}`,fragmentShader:`varying float v;void main(){gl_FragColor=vec4(.65,1.,.38,.12+abs(v)*.14);}`});const core=new THREE.Mesh(coreGeo,coreMat);group.add(core);
let tx=0,ty=0,x=0,y=0;window.addEventListener('pointermove',e=>{tx=(e.clientX/innerWidth-.5);ty=(e.clientY/innerHeight-.5);pm.uniforms.uPointer.value.set(tx,ty)});
let scroll=0;window.addEventListener('scroll',()=>scroll=scrollY,{passive:true});
const clock=new THREE.Clock();function frame(){const t=clock.getElapsedTime();pm.uniforms.uTime.value=t;coreMat.uniforms.uTime.value=t;x+=(tx-x)*.035;y+=(ty-y)*.035;group.rotation.y=t*.035+x*.18;group.rotation.x=y*.1;particles.rotation.z=t*.012;ring.rotation.z=-t*.08;camera.position.z=12+Math.min(scroll/1000,2.2);camera.position.x=x*.5;camera.position.y=-y*.35;camera.lookAt(0,0,0);renderer.render(scene,camera);requestAnimationFrame(frame)}frame();
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight)});
// subtle reveal on scroll
const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('seen')}),{threshold:.12});$$('.section,.manifesto,.footer').forEach(e=>obs.observe(e));
})();
